### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by balakrishnangithub** [triump0870/Kivy_Python#1]
```
[INFO   ] Kivy v1.8.0-dev
[INFO   ] [Logger      ] Record log in /home/bk/.kivy/logs/kivy_13-11-10_63.txt
[INFO   ] [Factory     ] 155 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60s
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif 
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
[DEBUG  ] [App         ] Loading kv <./pong.kv>
[DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
[INFO   ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[DEBUG  ] [Window      ] Display driver x11
[DEBUG  ] [Window      ] Actual window size: 1025x768
[DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a0
[DEBUG  ] [Window      ] Actual depth bits: 24
[DEBUG  ] [Window      ] Actual stencil bits: 8
[DEBUG  ] [Window      ] Actual multisampling samples: 2
[INFO   ] [GL          ] OpenGL version <3.0 Mesa 9.2.1>
[INFO   ] [GL          ] OpenGL vendor <nouveau>
[INFO   ] [GL          ] OpenGL renderer <Gallium 0.4 on NV96>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <1.30>
[INFO   ] [GL          ] Texture max size <8192>
[INFO   ] [GL          ] Texture max units <16>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImagePygame ] Load </usr/lib/python2.7/dist-packages/kivy/data/glsl/default.png>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [OSC         ] using <multiprocessing> for socket
[DEBUG  ] [Base        ] Create provider from mouse
[DEBUG  ] [Base        ] Create provider from probesysfs
[DEBUG  ] [ProbeSysfs  ] using probsysfs!
[INFO   ] [Base        ] Start application main loop
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "main.py", line 78, in <module>
     PongApp().run()
   File "/usr/lib/python2.7/dist-packages/kivy/app.py", line 623, in run
     runTouchApp()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 454, in runTouchApp
     EventLoop.window.mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 329, in mainloop
     self._mainloop()
   File "/usr/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 235, in _mainloop
     EventLoop.idle()
   File "/usr/lib/python2.7/dist-packages/kivy/base.py", line 294, in idle
     Clock.tick()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 370, in tick
     self._process_events()
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 481, in _process_events
     if event.tick(self._last_tick) is False:
   File "/usr/lib/python2.7/dist-packages/kivy/clock.py", line 280, in tick
     ret = callback(self._dt)
   File "main.py", line 48, in update
     self.player1.bounce_ball(self.ball)
 AttributeError: 'NoneType' object has no attribute 'bounce_ball'
```

**Comment by triump0870** [comment]
check your pong.kv file .. it may be indentation problem in Pongball class or in main.py bounce_ball function...
i already post a working pong game screen short

**Comment by balakrishnangithub** [comment]
took a long time
